# Generated by Django 3.1.2 on 2020-11-03 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import suap_ead.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', suap_ead.fields.StringField(max_length=250, verbose_name='Nome da agenda')),
                ('janela', models.PositiveIntegerField(help_text='Alterar a janela depois de já ter solicitações não muda a tempo da reserva da solicitação', verbose_name='Janela de atendimento (min)')),
                ('inicio', models.DateField(help_text='Esta agenda começa que dia? Alterar a data de início da agenda não altera as solicitações', verbose_name='Início')),
                ('fim', models.DateField(help_text='Esta agenda termina que dia. Alterar a data de fim da agenda não altera as solicitações', verbose_name='Fim')),
                ('informacao', models.TextField(blank=True, null=True, verbose_name='Informações aos solicitantes')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suap_id', suap_ead.fields.StringField(max_length=250, unique=True, verbose_name='ID no SUAP')),
                ('sigla', suap_ead.fields.StringField(max_length=250, unique=True, verbose_name='Sigla')),
                ('descricao', suap_ead.fields.StringField(max_length=250, verbose_name='Descrição')),
                ('url', models.URLField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('active', models.BooleanField(verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campi',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', suap_ead.fields.StringField(max_length=250, unique=True, verbose_name='Código')),
                ('nome', suap_ead.fields.StringField(max_length=250, verbose_name='Nome')),
                ('descricao', suap_ead.fields.StringField(max_length=250, verbose_name='Descrição')),
                ('active', models.BooleanField(verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', suap_ead.fields.StringField(choices=[('0', 'Seg'), ('1', 'Ter'), ('2', 'Qua'), ('3', 'Qui'), ('4', 'Sex'), ('5', 'Sab'), ('6', 'Dom')], max_length=250, verbose_name='Dia da semana')),
                ('inicio', models.TimeField(verbose_name='Início')),
                ('fim', models.TimeField(verbose_name='Fim')),
                ('atendimentos', models.PositiveIntegerField(verbose_name='Quantidade de atendimentos na janela')),
                ('agenda', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agenda', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['dia', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', suap_ead.fields.StringField(max_length=250, unique=True, verbose_name='Código')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('curso', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Agendado para')),
                ('fim', models.DateTimeField(verbose_name='Termina em')),
                ('status', suap_ead.fields.StringField(choices=[('Solicitado', 'Solicitado'), ('Deferido', 'Deferido'), ('Indeferido', 'Indeferido'), ('Cancelado', 'Cancelado')], default='Solicitado', max_length=250, verbose_name='Status')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('agenda', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agenda', verbose_name='Agenda')),
                ('avaliador', suap_ead.fields.NullFK(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliadores', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('solicitante', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', suap_ead.fields.StringField(max_length=250, unique=True, verbose_name='Sigla')),
                ('descricao', suap_ead.fields.StringField(max_length=250, verbose_name='Descrição')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('campus', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.campus', verbose_name='Campus')),
            ],
            options={
                'verbose_name': 'Diretoria',
                'verbose_name_plural': 'Diretorias',
                'ordering': ['sigla'],
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='diretoria',
            field=suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.diretoria', verbose_name='Diretoria'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='restrito_aas_diretorias',
            field=models.ManyToManyField(blank=True, to='agendamento.Diretoria'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='restrito_aas_turmas',
            field=models.ManyToManyField(blank=True, to='agendamento.Turma'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='restrito_aos_campi',
            field=models.ManyToManyField(blank=True, to='agendamento.Campus'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='restrito_aos_cursos',
            field=models.ManyToManyField(blank=True, to='agendamento.Curso'),
        ),
    ]
