# Generated by Django 3.1.2 on 2020-10-28 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import suap_ead.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', suap_ead.fields.StringField(max_length=250, verbose_name='Nome da agenda')),
                ('janela', models.PositiveIntegerField(help_text='Alterar a janela depois de já ter solicitações não muda a tempo da reserva da solicitação', verbose_name='Janela de atendimento (min)')),
                ('inicio', models.DateField(help_text='Esta agenda começa que dia? Alterar a data de início da agenda não altera as solicitações', verbose_name='Início')),
                ('fim', models.DateField(help_text='Esta agenda termina que dia. Alterar a data de fim da agenda não altera as solicitações', verbose_name='Fim')),
                ('informacao', models.TextField(blank=True, null=True, verbose_name='Informações aos solicitantes')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
                'ordering': ['inicio'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', suap_ead.fields.StringField(choices=[('1', 'Dom'), ('2', 'Seg'), ('3', 'Ter'), ('4', 'Qua'), ('5', 'Qui'), ('6', 'Sex'), ('7', 'Sab')], max_length=250, verbose_name='Dia da semana')),
                ('inicio', models.TimeField(verbose_name='Início')),
                ('fim', models.TimeField(verbose_name='Fim')),
                ('atendimentos', models.PositiveIntegerField(verbose_name='Quantidade de atendimentos na janela')),
                ('agenda', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agenda', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['dia', 'inicio'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Agendado para')),
                ('fim', models.DateTimeField(verbose_name='Termina em')),
                ('status', suap_ead.fields.StringField(choices=[('Solicitado', 'Solicitado'), ('Deferido', 'Deferido'), ('Indeferido', 'Indeferido')], default='Solicitado', max_length=250, verbose_name='Status')),
                ('justificativa', models.TextField(blank=True, null=True, verbose_name='Justificativa')),
                ('agenda', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agenda', verbose_name='Agenda')),
                ('avaliador', suap_ead.fields.NullFK(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliadores', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador')),
                ('solicitante', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, related_name='solicitantes', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['inicio'],
            },
        ),
    ]
