# Generated by Django 3.1.2 on 2020-11-03 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import suap_ead.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autorizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('agenda', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agenda', verbose_name='Agenda')),
                ('grupo', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Papel')),
                ('user', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Autorização',
                'verbose_name_plural': 'Autorizações',
                'ordering': ['active', 'grupo', 'user'],
            },
        ),
    ]
