# Generated by Django 3.1.2 on 2020-11-06 16:39

from django.db import migrations, models
import django.db.models.deletion
import suap_ead.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_auto_20201103_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaCriterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(verbose_name='Ativo')),
                ('agenda', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agenda', verbose_name='Agenda')),
            ],
            options={
                'verbose_name': 'Critério da agenda',
                'verbose_name_plural': 'Critérios das agendas',
                'ordering': ['criterio__titulo'],
            },
        ),
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', suap_ead.fields.StringField(max_length=250, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'Título',
                'verbose_name_plural': 'Títulos',
                'ordering': ['titulo'],
            },
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='avaliado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Avaliado em'),
        ),
        migrations.AlterField(
            model_name='diretoria',
            name='sigla',
            field=suap_ead.fields.StringField(max_length=250, verbose_name='Sigla'),
        ),
        migrations.AlterUniqueTogether(
            name='diretoria',
            unique_together={('campus', 'sigla')},
        ),
        migrations.CreateModel(
            name='CriterioAvaliado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confere', models.BooleanField(verbose_name='Confere')),
                ('criterio', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.agendacriterio', verbose_name='Critério')),
                ('solicitacao', suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.solicitacao', verbose_name='Solicitacao')),
            ],
            options={
                'verbose_name': 'Critério avaliado',
                'verbose_name_plural': 'Critérios avaliados',
                'ordering': ['criterio__criterio__titulo'],
            },
        ),
        migrations.AddField(
            model_name='agendacriterio',
            name='criterio',
            field=suap_ead.fields.FK(on_delete=django.db.models.deletion.CASCADE, to='agendamento.criterio', verbose_name='Critério'),
        ),
        migrations.AlterUniqueTogether(
            name='agendacriterio',
            unique_together={('agenda', 'criterio')},
        ),
    ]
