# Generated by Django 3.1.2 on 2020-11-06 17:47

from django.db import migrations, models
import suap_ead.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_auto_20201106_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoVinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', suap_ead.fields.StringField(max_length=250, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'ordering': ['descricao'],
            },
        ),
        migrations.AlterModelOptions(
            name='criterio',
            options={'ordering': ['titulo'], 'verbose_name': 'Critério', 'verbose_name_plural': 'Critérios'},
        ),
    ]
