# Generated by Django 3.1.2 on 2020-11-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0005_auto_20201106_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='restrito_aos_vinculos',
            field=models.ManyToManyField(blank=True, to='agendamento.TipoVinculo', verbose_name='Restrito às vínculos'),
        ),
    ]
